export { default as WebNavbar } from './webNavbar/WebNavbar';
export { default as LinkButton } from './linkButton/LinkButton';
export { default as Footer } from './footer/Footer';
// export { default as Heading1 } from './heading1/Heading1';
export { default as Heading2 } from './heading2/Heading2';
export { default as Heading3 } from './heading3/Heading3';
export { default as ParaText2 } from './paraText2/ParaText2';
export { default as ParaText3 } from './paraText3/ParaText3';
export { default as StatsItem } from './statsItem/StatsItem';
export { default as GlobeBanner } from './globeBanner/GlobeBanner';
export { default as ContentCard } from './contentCard/ContentCard';
export { default as Sidebar } from './sidebar/Sidebar';